export const items=[
    {
        id:'1',
        categort:'mobiles',
        title:'Apple iphone 14',
        imgSrc:'https://m.media-amazon.com/images/I/61bK6PMOC3L._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/3PukZp',
        description:'Apple iphone 14 (128 GB) - Blue',
        price:'89999',
    },
    {
        id:'5',
        categort:'laptops',
        title:'Xiaomi [SmartChoice] NoteBookPro',
        imgSrc:'https://m.media-amazon.com/images/I/71jnvo71a9L._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/3EzeQac',
        description:'Xiaomi [Smartchoice] NoteBookPro',
        price:'49999',
    },
    {
        id:'7',
        categort:'tablets',
        title:'Xiaomi pad 6',
        imgSrc:'https://m.media-amazon.com/images/I/71Mt4JAZQtL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/3ZeNRdY',
        description:'Xiaomi Pad 6| Qualcomn Snapdragon 870|',
        price:'29999',
    },
    {
        id:'2',
        categort:'mobiles',
        title:'Apple iphone 11',
        imgSrc:'https://m.media-amazon.com/images/I/7182vuseLqS._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/44MiYi6',
        description:'Apple iphone 11 (64 GB) - White',
        price:'79999',
    },
    {
        id:'6',
        categort:'tablets',
        title:'Lenovo Tab P12 Pro AMOLED',
        imgSrc:'https://m.media-amazon.com/images/I/616SXS5m0eL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/44MiYi6',
        description:'Lenov Tab P12 Pro AMOLD (12.6 inch (32 cm), 8 GB, 256 GB, wi-fi only), Storm Gray Preecision Pen 3)',
        price:'19999',
    },
    {
        id:'3',
        categort:'mobiles',
        title:'Aplle iphone 13',
        imgSrc:'https://m.media-amazon.com/images/I/71xb2xkN5qL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/3r6xJtv',
        description:'Apple iphone 13 (12 GB)- Blue',
        price:'69999',
    },
    {
        id:'4',
        categort:'laptops',
        title:'Lenovo IdaePad Slim  5',
        imgSrc:'https://m.media-amazon.com/images/I/71maiDRnoiL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/44JsK4r',
        description:'Lenovo IdeaPad Slim 5 Intel Core is 124450H 14" (35.5cm)',
        price:'29999',
    },
    {
        id:'9',
        categort:'tablets',
        title:'Samsung Galexy Tab AB',
        imgSrc:'https://m.media-amazon.com/images/I/61d46oYQgdL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/3Pdsh4F',
        description:'Lenovo IdeaPad Slim 5 Intel Core is 124450H 14" (35.5cm)',
        price:'29999',
    },
    {
        id:'8',
        categort:'laptops',
        title:'Apple MacBook Air Laptop',
        imgSrc:'https://m.media-amazon.com/images/I/71WkDp--uqL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/3r9rvhm',
        description:'Apple Macbook Air Laptop M1 chip, 13.3-inch/33.74 cem Retina Display',
        price:'89999',
    },
    {
        id:'10',
        categort:'mobiles',
        title:'Apple iphone 14 Pro',
        imgSrc:'https://m.media-amazon.com/images/I/61XO4bORHUL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/3PukZp',
        description:'Apple iphone 14 (128 GB) - Black',
        price:'89999',
    },
    {
        id:'14',
        categort:'laptops',
        title:'Xiaomi [SmartChoice] NoteBook',
        imgSrc:'https://m.media-amazon.com/images/I/71jnvo71a9L._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/3EzeQac',
        description:'Xiaomi [Smartchoice] NoteBookPro',
        price:'49999',
    },
    {
        id:'16',
        categort:'tablets',
        title:'Redmi Pad SE',
        imgSrc:'https://m.media-amazon.com/images/I/51HWtKW8swL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/3ZeNRdY',
        description:'Redmi Pad SE| All Day Battery | Qualcomm Snapdragon 680| 90Hz Refresh Rate|',
        price:'29999',
    },
    {
        id:'11',
        categort:'mobiles',
        title:'Apple iphone 12',
        imgSrc:'https://m.media-amazon.com/images/I/711wsjBtWeL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/44MiYi6',
        description:'Apple iphone 12 (64 GB) - White',
        price:'79999',
    },
    {
        id:'15',
        categort:'tablets',
        title:'Lenovo Tab M11 with Pen',
        imgSrc:'https://m.media-amazon.com/images/I/51WLV2ZemjL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/44MiYi6',
        description:'Lenov Tab P12 Pro AMOLD (12.6 inch (32 cm), 8 GB, 256 GB, wi-fi only), Storm Gray Preecision Pen 3)',
        price:'19999',
    },
    {
        id:'12',
        categort:'mobiles',
        title:'Aplle iphone 13',
        imgSrc:'https://m.media-amazon.com/images/I/61l9ppRIiqL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/3r6xJtv',
        description:'Apple iphone 13 (12 GB)- pink',
        price:'69999',
    },
    {
        id:'13',
        categort:'laptops',
        title:'Lenovo laptops v15 G2 ',
        imgSrc:'https://m.media-amazon.com/images/I/71MuvuEjyAL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/44JsK4r',
        description:'Lenovo IdeaPad Slim 5 Intel Core is 124450H 14" (35.5cm)',
        price:'29999',
    },
    {
        id:'18',
        categort:'tablets',
        title:'Samsung Galexy Tab Pro 5g',
        imgSrc:'https://m.media-amazon.com/images/I/71wkgHCzagL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/3Pdsh4F',
        description:'Lenovo IdeaPad Slim 5 Intel Core is 124450H 14" (35.5cm)',
        price:'29999',
    },
    {
        id:'17',
        categort:'laptops',
        title:'Apple MacBook Air Laptop M1 chip',
        imgSrc:'https://m.media-amazon.com/images/I/71jG+e7roXL._AC_UY327_FMwebp_QL65_.jpg',
        AmazonLink:'https://amzn.to/3r9rvhm',
        description:'Apple Macbook Air Laptop M1 chip, 13.3-inch/33.74 cem Retina Display',
        price:'89999',
    },
]